{{- $payload := include "arc-runners.nixConfig" . }}
{{- if $payload }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "arc-runners.nixConfigName" . }}
  labels:
    app.kubernetes.io/name: runner-nix-config
    app.kubernetes.io/part-of: gha-rs
data:
  nix.conf: |
    {{- $payload | nindent 4 }}
  {{- if .Values.nixBuilders.enabled }}
  machines.template: |-
    {{- include "arc-runners.nixMachines" . | nindent 4 }}
  ssh_config: |-
    {{- include "arc-runners.nixSSHConfig" . | nindent 4 }}
  openbao-ca.crt: |-
    {{- .Values.nixBuilders.openbao.caBundle | b64dec | nindent 4 }}
  ssh-user-ca.pub: |-
    {{- join "\n" .Values.nixBuilders.openbao.sshCAPublicKeys | nindent 4 }}
  job-started.sh: |-
    {{- include "arc-runners.nixJobStartedHook" . | nindent 4 }}
  {{- end }}
immutable: true
{{- end }}
